service:
  port: 8080

eureka:
  url: http://localhost:8761/eureka

db:
  url: jdbc:postgresql://localhost:5432/auth
  username: postgres
  password: password
  driver: org.postgresql.Driver
  dialect: org.hibernate.dialect.PostgreSQLDialect
