
spring:
  datasource:
    password: ${datasources.postgresql.password}
    url: jdbc:postgresql://postgres:${datasources.postgresql.port}/auth
    username: ${datasources.postgresql.username}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:${microservices.eureka-server.port}/eureka
      