server:
  port: 8082

eureka:
  url: http://localhost:8761/eureka

db:
  url: jdbc:postgresql://localhost:5432/city
  username: postgres
  password: password
  driver: org.postgresql.Driver
  dialect: org.hibernate.dialect.PostgreSQLDialect    
